// apps/portfolio-page-angular/src/app/landing-page/components/about/about.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'pb-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AboutComponent {}

<section id="about">
  <h2 class="about--heading">Hi, I'm Pascal</h2>
  <div class="about--text">
    a Developer and Designer from South Germany. I'm currently working for the IT Department of a Finance and
    Insurance
    Company as an Web Frontend Developer.
  </div>
  <a class="btn btn-primary mt-lg" [routerLink]="['']">Learn more about me</a>
</section>

// apps/portfolio-page/src/app/components/about/about.component.tsx
import React from 'react';
import AboutContainer from './about.styles';

const About = () => (
  <AboutContainer>
    <p className="text">
      <span className="text--highlight"> Hi, I'm Pascal </span>
      <br />a Developer and Designer from South Germany. I'm currently working
      for the IT Department of a Finance and Insurance Company as a Web Frontend
      Developer. 
    </p>
  </AboutContainer>
);

export default About;
