// apps/portfolio-page/src/app/components/tech-stack/tech-stack.component.tsx
import React from 'react';
import {
  TechStackBackgroundImg,
  TechStackContainer,
  TechStackTechList,
  TechStackTechListItem,
  TechStackTextContent
} from './tech-stack.styles';
import AngularLogo from '../../../assets/img/logos/angular-logo.png';
import TypeScriptLogo from '../../../assets/img/logos/typescript-logo.png';
import JavaScriptLogo from '../../../assets/img/logos/javascript-logo.png';
import NodeJsLogo from '../../../assets/img/logos/nodejs-logo.png';
import SassLogo from '../../../assets/img/logos/sass-logo.png';

const TechStack = () => {
  const technologies: { title: string; logo: string }[] = [
    { title: 'Angular', logo: AngularLogo },
    { title: 'TypeScript', logo: TypeScriptLogo },
    { title: 'JavaScript', logo: JavaScriptLogo },
    { title: 'Node.js', logo: NodeJsLogo },
    { title: 'SASS', logo: SassLogo }
  ];

  return (
    <TechStackContainer>
      <TechStackBackgroundImg />
      <TechStackTextContent>
        <h2 className="heading-2">My Tech Stack</h2>
        <p className="tech-stack__text">
          Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam
          nonumy.
        </p>
      </TechStackTextContent>
      <TechStackTechList>
        {technologies.map((technology, i) => (
          <TechStackTechListItem key={i}>
            <img
              src={technology.logo}
              alt={technology.title}
              className="tech-stack-list__item-img"
            />
          </TechStackTechListItem>
        ))}
      </TechStackTechList>
    </TechStackContainer>
  );
};

export default TechStack;

// apps/portfolio-page-angular/src/app/landing-page/components/tech-stack/tech-stack.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'pb-tech-stack',
  templateUrl: './tech-stack.component.html',
  styleUrls: ['./tech-stack.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class TechStackComponent {}

<section id="tech-stack-section">
  <div class="container--top">
    <h2>My Tech Stack</h2>
    <p class="container--top-text">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy.</p>
  </div>
  <div class="tech-stack--box">
    <div class="tech-stack--box-1">
      <img src="/assets/img/angular-logo.png" alt="Angular Logo">
      <span>Angular</span>
    </div>
    <div class="tech-stack--box-2">
      <img src="/assets/img/typescript-logo.png" alt="TypeScript Logo">
      <span>TypeScript</span>
    </div>
    <div class="tech-stack--box-3">
      <img src="/assets/img/javascript-logo.png" alt="JavaScript Logo">
      <span>JavaScript</span>
    </div>
    <div class="tech-stack--box-4">
      <img src="/assets/img/sass-logo.png" alt="SASS Logo">
      <span>Sass</span>
    </div>
    <div class="tech-stack--box-5">
      <img src="/assets/img/nodejs-logo.png" alt="NodeJs Logo">
      <span>NodeJs</span>
    </div>
  </div>
  <div class="container--bottom">
    <a [routerLink]="['']" class="btn btn-primary">View all</a>
  </div>
</section>
